// src/app/core/services/marker.service.ts
import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { catchError } from 'rxjs/operators';
import { Marker } from '../../core/models/marker.model'; // Adjust path if needed

// Consider defining this in environments/environment.ts
const API_URL = 'http://localhost:5000/markers';

@Injectable({
  providedIn: 'root', // Makes this service available application-wide
})

export class MarkerService {

  private apiUrl = API_URL;

  constructor(private http: HttpClient) {}

  /**
   * Fetches all markers from the backend.
   * @returns An Observable emitting an array of Marker objects.
   */

  getMarkers(): Observable<Marker[]> {
    return this.http.get<Marker[]>(this.apiUrl).pipe(
      catchError(this.handleError)
    );
  }

  /**
   * Adds a new marker to the backend.
   * @param marker The Marker object to add (without the ID, as it's generated by backend).
   * @returns An Observable emitting the created marker (with its ID).
   */

  addMarker(marker: Omit<Marker, 'id'>): Observable<{ id: string }> {
    return this.http.post<{ id: string }>(this.apiUrl, marker).pipe(
      catchError(this.handleError)
    );
  }

  /**
   * Deletes a marker by its ID.
   * @param id The ID of the marker to delete.
   * @returns An Observable indicating completion.
   */
  deleteMarker(id: string): Observable<void> {
    return this.http.delete<void>(`${this.apiUrl}/${id}`).pipe(
      catchError(this.handleError)
    );
  }



// src/app/core/services/marker.service.ts
// Ajoutez cette méthode
updateMarker(marker: Marker): Observable<Marker> {
  const url = `${this.apiUrl}/${marker.id}`;
  return this.http.put<Marker>(url, marker).pipe(
    catchError(this.handleError)
  );
}















  // --- Error Handling ---
  private handleError(error: HttpErrorResponse) {
    let errorMessage = 'An unknown error occurred!';
    if (error.error instanceof ErrorEvent) {
      // A client-side or network error occurred.
      errorMessage = `Error: ${error.error.message}`;
    } else {
      // The backend returned an unsuccessful response code.
      errorMessage = `Error Code: ${error.status}\nMessage: ${error.message}`;
      if (error.error && typeof error.error === 'string') {
        errorMessage += `\nDetails: ${error.error}`;
      } else if (error.error && typeof error.error === 'object') {
        // Try to get a more specific message from the backend error object
        errorMessage += `\nDetails: ${JSON.stringify(error.error)}`;
      }
    }
    console.error(errorMessage); // Log the error for debugging
    // Return an observable with a user-facing error message.
    return throwError(() => new Error(errorMessage));
  }
}
